// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Victor_Ferreiras_P2_AP1.DAL;

#nullable disable

namespace Victor_Ferreiras_P2_AP1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250318120205_EncuestasDetalleArreglado")]
    partial class EncuestasDetalleArreglado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Victor_Ferreiras_P2_AP1.Models.Ciudades", b =>
                {
                    b.Property<int>("CiudadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CiudadId"));

                    b.Property<string>("CiudadNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.HasKey("CiudadId");

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            CiudadId = 1,
                            CiudadNombre = "San Francisco",
                            Monto = 0.0
                        },
                        new
                        {
                            CiudadId = 2,
                            CiudadNombre = "Santiago",
                            Monto = 0.0
                        },
                        new
                        {
                            CiudadId = 3,
                            CiudadNombre = "Santo Domingo",
                            Monto = 0.0
                        });
                });

            modelBuilder.Entity("Victor_Ferreiras_P2_AP1.Models.Encuestas", b =>
                {
                    b.Property<int>("EncuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EncuestaId"));

                    b.Property<string>("Asignatura")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("FechaEncuesta")
                        .HasColumnType("datetime2");

                    b.Property<double>("MontoTotal")
                        .HasColumnType("float");

                    b.HasKey("EncuestaId");

                    b.ToTable("Encuestas");
                });

            modelBuilder.Entity("Victor_Ferreiras_P2_AP1.Models.EncuestasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<int>("EncuestaId")
                        .HasColumnType("int");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.HasKey("DetalleId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("EncuestaId");

                    b.ToTable("EncuestasDetalle");
                });

            modelBuilder.Entity("Victor_Ferreiras_P2_AP1.Models.EncuestasDetalle", b =>
                {
                    b.HasOne("Victor_Ferreiras_P2_AP1.Models.Ciudades", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Victor_Ferreiras_P2_AP1.Models.Encuestas", "Encuestas")
                        .WithMany("EncuestasDetalles")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");

                    b.Navigation("Encuestas");
                });

            modelBuilder.Entity("Victor_Ferreiras_P2_AP1.Models.Encuestas", b =>
                {
                    b.Navigation("EncuestasDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
